// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK0pxawj5LjHho55i0lgx0L3Ea_ziV2c0',
    appId: '1:980095635244:web:2f356902d8b4a0cfa82689',
    messagingSenderId: '980095635244',
    projectId: 'leafy-pbl',
    authDomain: 'leafy-pbl.firebaseapp.com',
    storageBucket: 'leafy-pbl.firebasestorage.app',
    measurementId: 'G-GLG0EPB8HX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIvi0_bAy3gOA7KwRwH0O0L6OrjocUZxQ',
    appId: '1:980095635244:android:269e04a73bc8af13a82689',
    messagingSenderId: '980095635244',
    projectId: 'leafy-pbl',
    storageBucket: 'leafy-pbl.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv8T4ho-IsADaEkSlZfISaOFOzecWGaZo',
    appId: '1:980095635244:ios:d8a72d73ab31ca2ea82689',
    messagingSenderId: '980095635244',
    projectId: 'leafy-pbl',
    storageBucket: 'leafy-pbl.firebasestorage.app',
    iosBundleId: 'com.example.leafy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv8T4ho-IsADaEkSlZfISaOFOzecWGaZo',
    appId: '1:980095635244:ios:d8a72d73ab31ca2ea82689',
    messagingSenderId: '980095635244',
    projectId: 'leafy-pbl',
    storageBucket: 'leafy-pbl.firebasestorage.app',
    iosBundleId: 'com.example.leafy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCK0pxawj5LjHho55i0lgx0L3Ea_ziV2c0',
    appId: '1:980095635244:web:bf2c6a396662c084a82689',
    messagingSenderId: '980095635244',
    projectId: 'leafy-pbl',
    authDomain: 'leafy-pbl.firebaseapp.com',
    storageBucket: 'leafy-pbl.firebasestorage.app',
    measurementId: 'G-D7EJ2ZW3ZW',
  );
}
